preset: psr2
risky: true

finder:
  path:
    - "src/"
    - "tests/"
  name:
    - "*.php"

enabled:
  - array_short_syntax
  - binary_operator_spaces
  - blank_line_after_opening_tag
  - blank_line_before_return
  - cast_spaces
  - combine_consecutive_unsets
  - declare_strict_types
  - doctrine_annotation_braces
  - doctrine_annotation_indentation
  - doctrine_annotation_spaces
  - function_to_constant
  - function_typehint_space
  - hash_to_slash_comment
  - include
  - is_null
  - linebreak_after_opening_tag
  - short_list_syntax
  - lowercase_cast
  - magic_constant_casing
  - method_separation
  - modernize_types_casting
  - native_function_casing
  - new_with_braces
  - no_alias_functions
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - print_to_echo
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_short_bool_cast
  - no_short_echo_tag
  - no_singleline_whitespace_before_semicolons
  - no_spaces_around_offset
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_unneeded_control_parentheses
  - no_unreachable_default_argument_value
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - non_printable_character
  - normalize_index_brace
  - phpdoc_add_missing_param_annotation
  - php_unit_fqcn_annotation
  - phpdoc_align
  - object_operator_without_whitespace
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_return_self_reference
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_single_line_var_spacing
  - phpdoc_summary
  - phpdoc_trim
  - phpdoc_types
  - phpdoc_var_without_name
  - pre_increment
  - protected_to_private
  - psr4
  - return_type_declaration
  - semicolon_after_instruction
  - short_scalar_cast
  - single_blank_line_before_namespace
  - single_quote
  - space_after_semicolon
  - standardize_not_equals
  - ternary_operator_spaces
  - ternary_to_null_coalescing
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unary_operator_spaces
  - const_visibility_required
  - property_visibility_required
  - method_visibility_required
  - whitespace_after_comma_in_array
  - pow_to_exponentiation
  - no_php4_constructor
  - ereg_to_preg

disabled:
  - general_phpdoc_annotation_remove
  - native_function_invocation
  - mb_str_functions
  - no_blank_lines_before_namespace
  - header_comment
  - heredoc_to_nowdoc
  - class_keyword_remove
  - php_unit_test_class_requires_covers
  - not_operator_with_space
  - not_operator_with_successor_space
  - ordered_class_elements
  - ordered_imports
  - php_unit_construct
  - php_unit_dedicate_assert
  - php_unit_strict
  - phpdoc_to_comment
  - phpdoc_type_to_var
  - dir_constant
  - align_double_arrow
  - align_equals
  - class_keyword_remove
  - phpdoc_annotation_without_dot
  - strict_comparison
  - strict_param
  - psr0
  - self_accessor
  - silenced_deprecation_error
  - simplified_null_return
  - random_api_migration
