# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

# Tell Travis CI we are using PHP
language: php

# Versions of PHP you want your project run with.
php:
  - 7.1

# The platforms you wants to test on
os:
  - linux

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# We don't want to run linux commands as super user
sudo: false

# You can delete cache using travis-ci web interface
cache:
  directories:
    - $HOME/.php-cs-fixer
    - $HOME/.cache/composer
    - vendor

# Commands to be run before your environment runs.
before_script:
  - travis_retry make ci_before_build

# Commands you want to run that will verify your build.
script:
  - make ci_build

after_script:
# Commands to be run after your environment runs.
  - travis_retry make ci_after_build

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Configure email notifications
notifications:
  email:
    on_success: never
    on_failure: always
